### ISSUE TITLE
Test Addressables compression

### ISSUE THREAD

**Issue by dbirman** [dbirman/VirtualBrainLab#9]
- [x] Mark the .bytes file as addressable & assign to its own group
- [x] Build Addressables
- [x] In the Addressables build folder check the size of the .bundle file generated for the new group

**Comment by KaiNylund** [comment]
Uncompressed baselined averages bytes file: 789mb
Addressables remote build of the same file with LZ4 compression: 649mb
Addressables remote build of the same file with LZMA compression: 518mb

LZMA compression took much longer than LZ4, but looks like the better option?
